language: python
install:
 - git clone https://github.com/w3c/respec.git
 - git clone https://github.com/dontcallmedom/webidl-checker.git
 - git clone https://github.com/dontcallmedom/widlproc
 - git clone https://github.com/halindrome/linkchecker.git
 - cd widlproc && make obj/widlproc && cd ..
 - pip install html5lib lxml
 - sudo apt-get install libwww-perl
script:
 - phantomjs --ignore-ssl-errors=true --ssl-protocol=tlsv1 respec/tools/respec2html.js -e -w webrtc.html output.html
 - python webidl-checker/webidl-check output.html
 - "! (perl -T linkchecker/bin/checklink -S 0  -q -b output.html |grep  \"^\")"
env: WIDLPROC_PATH=$TRAVIS_BUILD_DIR/widlproc/obj/widlproc